name: Update submodule Pull Request
on:
  repository_dispatch:
    types: [update-submodule]

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_SECRET }}

      - uses: actions/checkout@main 
        with:
          submodules: true

      - run: git submodule update --remote

      - name: Create Pull Request 
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update submodule.
          labels: Auto PR
          branch: auto-pr/update-submodule 
          branch-suffix : timestamp 
          commit-message: auto update submodule
          base : main
          delete-branch: true
          token: ${{ steps.generate_token.outputs.token }}